### ISSUE TITLE
Title of section

### ISSUE THREAD

**Issue by DerouicheMedAziz** [DerouicheMedAziz/cv#1]
Create titles flexible over the screen size. And remove repetants title-section.

**Comment by DerouicheMedAziz** [comment]
Add media that centralizes the title if the screen under 768px:

``` css
@media (max-width: 767px) {
    .section-title{
        text-align: center;
    }
}
```

Remove all section-title:

``` html
<h3 class="hidden-xs title-section"><strong>//TITRE</strong></h3>  
<h3 class="visible-xs text-center title-section"><strong>// TITRE</strong></h3>
```

And add one `<h3>` tag of section-title class:

``` html
<h3 class="section-title"><strong>// TITRE</strong></h3>
```
