### ISSUE TITLE
Contact section

### ISSUE THREAD

**Issue by DerouicheMedAziz** [DerouicheMedAziz/cv#2]
Restructer and simplicity HTML elements, and use the `<i>` tag instead the `<span>` tag.

**Comment by DerouicheMedAziz** [comment]
New style of contact section:
```css
.contact-row{
    width: 100%;
    height: 40px;
    float: left;
}
.contact-icon{
    display: inline-block;
    width: 20%;
    height: 100%;
    padding: 5px;
    opacity: 0.3;
}
.contact-title{
    display: inline-block;
    width: 80%;
    height: 100%;
}
.title h5{
    line-height: 20px;
    vertical-align: middle;
}
```

New forme of contact item:
```html
<div class="contact-item">  
   <div class="contact-icon">  
      <i class="fa fa-xxx fa-2x"></i>  
   </div>  
   <div class="contact-content">  
      <h5>xxx xx xxx xxx</h5>  
   </div>  
</div>

**Comment by DerouicheMedAziz** [comment]
New style of contact section:

``` css
.contact-row{
    width: 100%;
    height: 40px;
    float: left;
}
.contact-icon{
    display: inline-block;
    width: 20%;
    height: 100%;
    padding: 5px;
    opacity: 0.3;
}
.contact-title{
    display: inline-block;
    width: 80%;
    height: 100%;
}
.title h5{
    line-height: 20px;
    vertical-align: middle;
}
```

New forme of contact item:

``` html
<div class="contact-item">  
   <div class="contact-icon">  
      <i class="fa fa-xxx fa-2x"></i>  
   </div>  
   <div class="contact-content">  
      <h5>xxx xx xxx xxx</h5>  
   </div>  
</div> 
```
